<?php
/**
 * Digital8_Timetable extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	Digital8
 * @package		Digital8_Timetable
 * @copyright  	Copyright (c) 2013
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Enrolment view widget template
 *
 * @category	Digital8
 * @package		Digital8_Timetable
 * @author Ultimate Module Creator
 */
?>
<?php $_enrolment = $this->getCurrentEnrolment();?>
<?php if ($_enrolment) :?>
	<div class="enrolment-widget-view">
		<h3><?php echo $_enrolment->getName()?></h3>
		<div>

		</div>
	</div>
<?php endif;?> 