<?php
/**
 * TurnkeyE Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0).
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to obtain it through the world-wide-web, please send
 * an email to info@turnkeye.com so we can send you a copy immediately.
 *
 * @category   Turnkeye
 * @package    Turnkeye_Testimonial
 * @copyright  Copyright (c) 2010-2012 TurnkeyE Co. (http://turnkeye.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * side box template of testimonials
 *
 * @category   Turnkeye
 * @package    Turnkeye_Testimonial
 * @author     Viacheslav Fedorenko <v.fedorenko@turnkeye.com>
 */

/**
 * @var $this Turnkeye_Testimonial_Block_Testimonial
 */
?>

<section id="testimonials">
	
	<?php $testimonials = $this->getTestimonials(); ?>
	<?php $i = 0;?>
	<?php if ($testimonials->count() > 0): ?>
	
	<h3 class="no-margin">Testimonials</h3>
	
	<div class="flexslider">
		<ul class="slides">
			<?php foreach ($testimonials as $testimonial): ?>
				<li>
					<span class="quote"><?php echo $testimonial->getTestimonialText(); ?></span>
					
					<author><?php echo $testimonial->getTestimonialName(); ?></author>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
	<?php endif;?>

</section>