<?php
/**
 * TurnkeyE Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0).
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to obtain it through the world-wide-web, please send
 * an email to info@turnkeye.com so we can send you a copy immediately.
 *
 * @category   Turnkeye
 * @package    Turnkeye_Testimonial
 * @copyright  Copyright (c) 2010-2012 TurnkeyE Co. (http://turnkeye.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * template of testimonials
 *
 * @category   Turnkeye
 * @package    Turnkeye_Testimonial
 * @author     Viacheslav Fedorenko <v.fedorenko@turnkeye.com>
 */

/**
 * @var $this Turnkeye_Testimonial_Block_Testimonial
 */
?>

<div id="testimonials">
	<?php $testimonials = $this->getTestimonials(); ?>
	<?php $i = 0;?>
	<?php if ($testimonials->count() > 0): ?>
		<?php foreach ($testimonials as $testimonial): ?>
			<div class="testimonial <?php $i++; echo ($i % 4 <= 1 || $i == 1 ? "dark" : "") ?>">
				<img src="<?php echo $this->getSkinUrl("images/icons/quote-bubble.png") ?>" class="icon" />
				<div>
				<?php if ($testimonial->getTestimonialImg()): ?>
					<img alt="<?php echo $testimonial->getTestimonialName(); ?>" src="<?php echo $this->getUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). $testimonial->getTestimonialImg() ?>" />
				<?php endif; ?>
				
				<span class="quote <?php echo (strlen($testimonial->getTestimonialText()) > 400 ? "tiny" : (strlen($testimonial->getTestimonialText()) > 350 ? "small" : "")) ?>"><?php echo $testimonial->getTestimonialText(); ?></span>
				<span class="author"><?php echo $testimonial->getTestimonialName(); ?></span>
			</div></div>
		<?php endforeach; ?>
	<?php endif;?>
</div>