<?php 
/**
 * Digital8_Timetable extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	Digital8
 * @package		Digital8_Timetable
 * @copyright  	Copyright (c) 2013
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Intake Enrolment list template
 *
 * @category	Digital8
 * @package		Digital8_Timetable
 * @author Ultimate Module Creator
 */
?>
<?php $_enrolments = $this->getEnrolments(); ?>
<?php if ($_enrolments->getSize() > 0) :?>
<div class="page-title enrolment-title">
	<h2><?php echo Mage::helper('timetable')->__('Enrolments') ?>:<?php echo $this->getIntake()->getName();?></h2>
</div>
<div class="enrolments-list-container">
	<?php foreach ($_enrolments as $_enrolment) : ?>
		<div class="enrolment-list-item">
			<a href="<?php echo $_enrolment->getEnrolmentUrl();?>" title="<?php echo $this->htmlEscape($_enrolment->getName()) ?>">
				<?php echo $_enrolment->getName(); ?>
			</a>

		</div>
	<?php endforeach;?>
</div>
<?php endif;?> 