<?php 
/**
 * Digital8_Timetable extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	Digital8
 * @package		Digital8_Timetable
 * @copyright  	Copyright (c) 2013
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * timetable rss feeds block
 * @category   	Digital8
 * @package		Digital8_Timetable
 * @author Ultimate Module Creator
 */
?>
<?php $_feeds = $this->getFeeds();?>
<?php if ($_feeds): ?>
<table class="data-table rss-table" id="rss-table-timetable" style="margin-top:20px">
	<col />
	<col width="1" />
	<thead>
		<tr>
			<th colspan="2"><?php echo Mage::helper('timetable')->__('Timetable Feeds') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($_feeds as $_feed): ?>
		<tr>
			<td><?php echo $_feed->getLabel() ?></td>
			<td><a href="<?php echo $_feed->getUrl() ?>" class="link-rss"><?php echo Mage::helper('timetable')->__('Get Feed'); ?></a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php endif; ?> 